### ISSUE TITLE
I don't know why I can't post a question in the treasure drop project

### ISSUE THREAD

**Issue by Suz1e** [Windows200000/test#1]
### Suggestion(s)

And whether the exe can support "unassociated treasure drop activities" because now there is progress on the web page, but it cannot be collected.

**Comment by Suz1e** [comment]
![QQ截图20240730033511](https://github.com/user-attachments/assets/f640f6e6-b1f1-4c40-b71f-023effcd4410)
This event, you must watch this event for 1 hour to get CDK and link your account.

**Comment by Windows200000** [comment]
@Suz1e Do you want unlinked campaigns?

From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.

**Comment by Windows200000** [comment]
And what do you mean by "you can't post question"?

**Comment by Suz1e** [comment]
No, I want to get activity without associated accounts

**Comment by Windows200000** [comment]
> No, I want to get activity without associated accounts

From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.
